### PR TITLE
#397: Categorized Go dependencies as 'unknown' if module name does not contain version number

### LINKED ISSUE #397: Categorize Go dependencies as 'unknown' if type cannot be determined pt. 2
This is a follow-up on https://github.com/exasol/project-keeper/issues/390
Running PK on branch https://github.com/exasol/exasol-driver-go/tree/use-exasol-test-setup fails with the following exception:

```
Exception in thread "main" java.lang.IllegalStateException: E-PK-CORE-158: Unknown suffix for module 'github.com/testcontainers/testcontainers-go'. This is an internal error that should not happen. Please report it by opening a GitHub issue.
        at com.exasol.projectkeeper.sources.analyze.golang.GolangDependencyType.getTypeByPrefix(GolangDependencyType.java:50)
        at com.exasol.projectkeeper.sources.analyze.golang.GolangDependencyType.getType(GolangDependencyType.java:31)
        at com.exasol.projectkeeper.shared.dependencychanges.DependencyChangeReport$Builder.mixed(DependencyChangeReport.java:147)
        at com.exasol.projectkeeper.sources.analyze.golang.GolangDependencyChangeCalculator.calculate(GolangDependencyChangeCalculator.java:38)
        at com.exasol.projectkeeper.sources.analyze.golang.GolangDependencyChangeCalculator.calculateDepencencyChanges(GolangDependencyChangeCalculator.java:16)
        at com.exasol.projectkeeper.sources.analyze.golang.GolangSourceAnalyzer.analyzeSource(GolangSourceAnalyzer.java:56)
        at com.exasol.projectkeeper.sources.analyze.golang.GolangSourceAnalyzer.lambda$analyze$0(GolangSourceAnalyzer.java:38)
```

### LINKED ISSUE #398: Loading NPM source fails when package.json did not exist in previous release
Running PK fix on branch https://github.com/exasol/extension-manager/tree/%2382-extension-registry fails with the following error, when an NPM source was added to `.project-keeper.yml`:

```yaml
  - type: npm
    path: registry/package.json
```

```
Exception in thread "main" java.lang.IllegalStateException: E-PK-CORE-134: File registry/package.json does not exist at tag 'v0.1.0'
        at com.exasol.projectkeeper.sources.analyze.generic.PreviousRelease.getContent(PreviousRelease.java:76)
        at com.exasol.projectkeeper.sources.analyze.generic.PreviousRelease.lambda$getContent$0(PreviousRelease.java:65)
        at java.base/java.util.Optional.map(Optional.java:265)
        at com.exasol.projectkeeper.sources.analyze.generic.PreviousRelease.getContent(PreviousRelease.java:65)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmServices.retrievePrevious(NpmServices.java:54)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmSourceAnalyzer.analyzeSource(NpmSourceAnalyzer.java:43)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmSourceAnalyzer.lambda$analyze$0(NpmSourceAnalyzer.java:36)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmSourceAnalyzer.analyze(NpmSourceAnalyzer.java:36)
        at com.exasol.projectkeeper.sources.SourceAnalyzer.analyzeSources(SourceAnalyzer.java:72)
        at com.exasol.projectkeeper.sources.SourceAnalyzer.analyze(SourceAnalyzer.java:61)
        at com.exasol.projectkeeper.ProjectKeeper.phase2(ProjectKeeper.java:126)
        at com.exasol.projectkeeper.ProjectKeeper.runValidationPhases(ProjectKeeper.java:225)
        at com.exasol.projectkeeper.ProjectKeeper.fix(ProjectKeeper.java:211)
        at com.exasol.projectkeeper.cli.ProjectKeeperLauncher.runProjectKeeper(ProjectKeeperLauncher.java:64)
        at com.exasol.projectkeeper.cli.ProjectKeeperLauncher.start(ProjectKeeperLauncher.java:59)
        at com.exasol.projectkeeper.cli.ProjectKeeperLauncher.main(ProjectKeeperLauncher.java:53)
Caused by: java.io.FileNotFoundException: E-PK-SMC-35: Failed to read file registry/package.json from commit '0e466789b85260d26534d4d2e21f8529c724f501'. Make sure that the file exists at the given commit.
        at com.exasol.projectkeeper.shared.repository.GitRepository.findFile(GitRepository.java:240)
        at com.exasol.projectkeeper.shared.repository.GitRepository.getFileFromCommit(GitRepository.java:182)
        at com.exasol.projectkeeper.sources.analyze.generic.PreviousRelease.getContent(PreviousRelease.java:71)
        ... 22 more
```

### PR DESCRIPTION
**Pull request by ckunki**
fixes #397
fixes #398

### CODE REVIEW

File: project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/generic/PreviousRelease.java [hunk 1]
```diff
@@ -70,10 +69,7 @@ private String getContent(final GitRepository repo, final TaggedCommit tag) {
         try {
             return repo.getFileFromCommit(this.file, tag.getCommit());
         } catch (final FileNotFoundException exception) {
-            throw new IllegalStateException(ExaError.messageBuilder("E-PK-CORE-134")
-                    .message("File {{module file}} does not exist at tag {{tag}}", //
-                            this.file, tag.getTag())
-                    .toString(), exception);
+            return null;
```
Comment (kaklakariada) [inline project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/generic/PreviousRelease.java:72]: Return Optional<String> and use `flatMap()` in `getContent()`.

**Review by kaklakariada — CHANGES_REQUESTED** [review]

**Review by kaklakariada — DISMISSED** [review]

**Review by kaklakariada — APPROVED** [review]
