### PR TITLE
bug/307: Fixed unreadable error when specifying go dir instead of go.mod

### LINKED ISSUE #307: Unreadable error when specifying go dir instead of go.mod
in a  multi project setup go projects can be in a nested folder.
In that case PK currenty fails with
```
2022-05-18 07:13:23.713 [FINE   ] Executing command 'go list -f {{if not .Indirect}}{{.}}{{end}} -m all' in working dir /home/jakob/exasol/exasol-test-setup-abstraction-server 
Exception in thread "main" java.lang.IllegalStateException: E-PK-CORE-126: Failed to run command 'go list -f {{if not .Indirect}}{{.}}{{end}} -m all', exit code was 1 after PT0.023671S. Output:
''
Error output:
'go: cannot match "all": go.mod file not found in current directory or any parent directory; see 'go help modules'
'
        at com.exasol.projectkeeper.sources.analyze.golang.SimpleProcess.getOutput(SimpleProcess.java:87)
        at com.exasol.projectkeeper.sources.analyze.golang.GolangServices.getModuleInfo(GolangServices.java:132)
        at com.exasol.projectkeeper.sources.analyze.golang.GolangSourceAnalyzer.analyzeSource(GolangSourceAnalyzer.java:51)
        at com.exasol.projectkeeper.sources.analyze.golang.GolangSourceAnalyzer.lambda$analyze$0(GolangSourceAnalyzer.java:40)

```

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #307

### CODE REVIEW

File: project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangSourceAnalyzer.java [hunk 1]
```diff
@@ -46,6 +47,11 @@ private AnalyzedSource analyzeSource(final Path projectDir, final Source source)
                     .message("Analyzing of {{type}} is not supported by GolangSourceAnalyzer", source.getType())
                     .ticketMitigation().toString());
         }
+        if (!source.getPath().getFileName().equals(Path.of("go.mod"))) {
+            throw new IllegalArgumentException(ExaError.messageBuilder("E-PK-CORE-133")
+                    .message("Invalid path {{path}} for go source.", source.getPath())
+                    .mitigation("The path must point to a  \"go.mod\" file.").toString());
```
Comment (morazow) [inline project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GolangSourceAnalyzer.java:53]:
```suggestion
                    .mitigation("The path must point to a \"go.mod\" file.").toString());
```

File: project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GolangSourceAnalyzerTest.java [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+
+    @Test
+    void testInvalidPath() {
+        final List<Source> sources = List.of(Source.builder().type(GOLANG).path(this.tempDir).build());
+        final GolangSourceAnalyzer analyzer = new GolangSourceAnalyzer(
+                ProjectKeeperConfig.builder().sources(sources).build());
+        final IllegalArgumentException exception = assertThrows(IllegalArgumentException.class,
+                () -> analyzer.analyze(this.tempDir, sources));
+        assertThat(exception.getMessage(), matchesPattern(
+                "\\QE-PK-CORE-133: Invalid path \\E.*\\Q for go source. The path must point to a  \"go.mod\" file.\\E"));
```
Comment (morazow) [inline project-keeper/src/test/java/com/exasol/projectkeeper/sources/analyze/golang/GolangSourceAnalyzerTest.java:30]:
```suggestion
                "\\QE-PK-CORE-133: Invalid path \\E.*\\Q for go source. The path must point to a \"go.mod\" file.\\E"));
```

**Review by morazow — CHANGES_REQUESTED** [review]

**Review by morazow — APPROVED** [review]

**Review by kaklakariada — APPROVED** [review]
