### PR TITLE
#602: Fixed customization of java version

### LINKED ISSUE #602: Customizing `actions/setup-java` does not work
When replacing or inserting a `actions/setup-java` step, PK always overwrites the Java version with the default (usually 11 and 17). This prevents customizing in case a specific version is required.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #602

### CODE REVIEW

File: project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/CiBuildWorkflowGenerator.java [hunk 1]
```diff
@@ -47,11 +47,12 @@ private FileTemplate createTemplate(final FileTemplateFromResource template, fin
         final List<StepCustomization> customizations = workflow.map(CustomWorkflow::getSteps)
                 .orElseGet(Collections::emptyList);
         final String environmentName = workflow.map(CustomWorkflow::getEnvironment).orElse(null);
-        return new ContentCustomizingTemplate(template, new GitHubWorkflowCustomizer(
+        return new ContentCustomizingTemplate(template, new GitHubWorkflowCustomizer( //
+                javaVersionCustomizer(),
```
Comment (tomuben) [inline project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/CiBuildWorkflowGenerator.java:51]: No update of the requirement tracing  needed?

Comment (tomuben) [reply project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/CiBuildWorkflowGenerator.java:51]: Ah, ok, this is actually a bugfix. So I guess in this case we don't need to update the requirement tracing.

**Review by tomuben — APPROVED** [review]
