### PR TITLE
614: Improve error message for unknown job ID in workflow customization

### LINKED ISSUE #614: Improve error handling for unknown jobs in workflow customization
When specifying an unknown job ID like in the following `.project-keeper.yml`, PK fix fails with a unhelpful error message

```yml
        - action: REPLACE
          job: unknown-job-id
          stepId: sonar-analysis
          content:
            name: Sonar analysis
            id: sonar-analysis
```

Error message:

```
Cannot invoke "com.exasol.projectkeeper.validators.files.GitHubWorkflow$Job.insertStepAfter(String, com.exasol.projectkeeper.shared.config.workflow.WorkflowStep)" because "job" is null
```

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #614

### CODE REVIEW

File: project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowStepCustomizer.java [hunk 1]
```diff
@@ -46,14 +46,14 @@ private Job getJob(final GitHubWorkflow workflow, final StepCustomization custom
...
         switch (customization.getType()) {
-        case REPLACE:
-            job.replaceStep(customization.getStepId(), customization.getStep());
-            break;
-        case INSERT_AFTER:
-            job.insertStepAfter(customization.getStepId(), customization.getStep());
-            break;
-        default:
-            throw new IllegalStateException("Unknown customization type: " + customization.getType());
+            case REPLACE:
```
Comment (redcatbear) [inline project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/GitHubWorkflowStepCustomizer.java:49]: Is this our official formatter setting? My memory says that the old variant is correct. Could you please check the settings?

**Review by redcatbear — APPROVED** [review]
