### PR TITLE
Bugfix/#296-fix-maven-central-deployment

### LINKED ISSUE #296: Fix templates for maven central deployment
The deployment to maven central is broken, see

* Failed build: https://github.com/exasol/test-db-builder-java/runs/6130267968?check_suite_focus=true
* Fix: https://github.com/exasol/test-db-builder-java/pull/98

See [documentation for setup-java action](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Apache-Maven)

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #296

See [documentation for setup-java action](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Apache-Maven)

### CODE REVIEW

File: release.sh [hunk 1]
```diff
@@ -1,16 +1,21 @@
 #!/bin/bash
-rm -rf ~/Downloads/pk-release/
-mkdir ~/Downloads/pk-release/
```
Comment (morazow) [inline release.sh:3]: Is this file required?

File: release.sh [hunk 2]
```diff
@@ -1,16 +1,21 @@
...
+
+version=2.3.2
```
Comment (morazow) [inline release.sh:3]: Maybe this should be set by using arguments?
```
./release.sh 2.3.2
```
And add set the `nounset` flag to check for unset variables.

**Review by morazow — CHANGES_REQUESTED** [review]

File: release.sh (hunk 1 above)
Comment (kaklakariada) [reply release.sh:3]: Yes, it is required, because release-droid does not yet support releasing project keeper. Until https://github.com/exasol/release-droid/issues/228 is implemented we need to release manually.

File: release.sh (hunk 2 above)
Comment (kaklakariada) [reply release.sh:3]: This is only a temporary solution until https://github.com/exasol/release-droid/issues/228 is fixed. I don't want to invest too much time into this workaround.

**Review by morazow — APPROVED** [review]
Looks good!
