### PR TITLE
#725: Fixed parsing NPM license arrays

### LINKED ISSUE #725: Project Keeper fix crashes on npm license array from license-checker
## Summary

`project-keeper fix` crashes with a `ClassCastException` while parsing npm license metadata from `license-checker`.

The crash happens after this command succeeds:

```text
npx license-checker --location=project --direct --json
```

`license-checker` can return a JSON array for the `licenses` field, but Project Keeper appears to parse it as `JsonString`.

## Reproduction

Repository: https://github.com/exasol/exasol-driver-ts

Run:

```sh
./.github/workflows/project-keeper.sh fix
```

## Relevant license-checker output

This direct dependency entry has an array value for `licenses`:

```text
pause-stream@0.0.11: ["MIT","Apache2"]
```

```json
  "pause-stream@0.0.11": {
    "licenses": [
      "MIT",
      "Apache2"
    ],
```

## Expected behavior

Project Keeper should handle `licenses` values that are JSON arrays by accepting multiple licenses.

## Actual behavior

Project Keeper crashes with:

```text
2026-04-29 10:55:11.579 [FINEST ] Command 'npx license-checker --location=project --direct --json' finished successfully after PT1.06648102S
Exception in thread "main" java.lang.ClassCastException: class org.eclipse.parsson.JsonArrayBuilderImpl$JsonArrayImpl cannot be cast to class jakarta.json.JsonString (org.eclipse.parsson.JsonArrayBuilderImpl$JsonArrayImpl and jakarta.json.JsonString are in unnamed module of loader 'app')
        at org.eclipse.parsson.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:244)
        at org.eclipse.parsson.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:249)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmLicense.jString(NpmLicense.java:24)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmLicense.from(NpmLicense.java:17)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmDependencies.lambda$convertLicenses$0(NpmDependencies.java:50)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:214)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:723)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmDependencies.convertLicenses(NpmDependencies.java:51)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmDependencies.retrieveNpmLicenses(NpmDependencies.java:45)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmDependencies.getDependencies(NpmDependencies.java:37)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmServices.getDependencies(NpmServices.java:53)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmSourceAnalyzer.analyzeSource(NpmSourceAnalyzer.java:50)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmSourceAnalyzer.lambda$analyze$0(NpmSourceAnalyzer.java:34)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:214)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1716)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:635)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:652)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:658)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:663)
        at com.exasol.projectkeeper.sources.analyze.npm.NpmSourceAnalyzer.analyze(NpmSourceAnalyzer.java:34)
        at com.exasol.projectkeeper.sources.SourceAnalyzer.analyzeSources(SourceAnalyzer.java:67)
        at com.exasol.projectkeeper.sources.SourceAnalyzer.analyze(SourceAnalyzer.java:58)
        at com.exasol.projectkeeper.ProjectKeeper.phase2AnalyzeSources(ProjectKeeper.java:137)
        at com.exasol.projectkeeper.ProjectKeeper.runValidationPhases(ProjectKeeper.java:276)
        at com.exasol.projectkeeper.ProjectKeeper.fix(ProjectKeeper.java:260)
        at com.exasol.projectkeeper.cli.ProjectKeeperLauncher.runProjectKeeper(ProjectKeeperLauncher.java:73)
        at com.exasol.projectkeeper.cli.ProjectKeeperLauncher.start(ProjectKeeperLauncher.java:67)
        at com.exasol.projectkeeper.cli.ProjectKeeperLauncher.main(ProjectKeeperLauncher.java:61)
```

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #725

### CODE REVIEW

File: project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/npm/NpmLicense.java [hunk 1]
```diff
@@ -1,40 +1,69 @@
...
 
 //[impl -> dsn~npm-dependency-licenses~1]
 record NpmLicense(String module, String version, String name, String url) {
 
     private static final Pattern PATTERN = Pattern.compile("^(.+)@([0-9]+(\\.[0-9]+)*+)$");
 
-    static NpmLicense from(final String moduleAndVersion, final JsonObject licenseInfos) {
+    static Map<String, List<NpmLicense>> from(final JsonObject json) {
+        return json.keySet().stream()
+                .collect(toMap(NpmLicense::moduleName, key -> NpmLicense.extract(key, json), NpmLicense::merge));
```
Comment (skyglass) [inline project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/npm/NpmLicense.java]:
```suggestion
                .collect(toMap(NpmLicense::moduleName, key -> extract(key, json), NpmLicense::merge));
```

File: project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/npm/NpmLicense.java [hunk 2]
```diff
@@ -1,40 +1,69 @@
...
+    }
+
+    private static List<NpmLicense> extract(final String moduleAndVersion, final JsonObject licenseInfos) {
         final JsonObject o = licenseInfos.getJsonObject(moduleAndVersion);
-        final String name = jString(o, "licenses");
         final String mainUrl = jString(o, "repository");
         final String[] p = split(moduleAndVersion);
```
Comment (skyglass) [inline project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/npm/NpmLicense.java:26]:
```suggestion
        final String[] p = split(moduleAndVersion);
        final String module = p[0];
        final String version = p[1];
```

File: project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/npm/NpmLicense.java [hunk 3]
```diff
@@ -1,40 +1,69 @@
...
-        return new NpmLicense(p[0], p[1], name, mainUrl);
+        return jStringList(o, "licenses").stream()
+                .map(name -> new NpmLicense(p[0], p[1], name, mainUrl))
```
Comment (skyglass) [inline project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/npm/NpmLicense.java]:
```suggestion
                .map(name -> new NpmLicense(module, version, name, mainUrl))
```

**Review by skyglass — COMMENTED** [review]
Some small suggestions

**Review by skyglass — APPROVED** [review]
