### PR TITLE
#533: Fix sonar warnings

### LINKED ISSUE #533: Fix sonar warnings after migration to Java 17
After migration to Java 17, Sonar complains that we should `record`s for immutable classes, `Stream.toList()` etc.

See https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&sinceLeakPeriod=true&id=com.exasol%3Aproject-keeper-root for the complete list.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #533

### CODE REVIEW

File: project-keeper/src/main/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRenderer.java [hunk 1]
```diff
@@ -63,7 +63,7 @@ private String buildDependencySectionForScope(final List<ProjectDependency> depe
             final BaseDependency.Type type, final MarkdownReferenceBuilder markdownReferenceBuilder,
             final int headlineLevel) {
         final List<ProjectDependency> dependenciesOfThisScope = dependencies.stream()
-                .filter(dependency -> dependency.getType().equals(type)).collect(Collectors.toList());
+                .filter(dependency -> dependency.getType().equals(type)).toList();
```
Comment (skyglass) [inline project-keeper/src/main/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRenderer.java:66]: It might throw exception if dependency.getType() == null
This one should also work:
`type.equals(dependency.getType())`

or you can try 
`Objects.equals(dependeny.getType(), type)` from `java.util`

File: project-keeper/src/test/java/com/exasol/projectkeeper/validators/ReadmeFileValidatorTest.java [hunk 2]
```diff
@@ -25,23 +25,29 @@ class ReadmeFileValidatorTest {
...
+
+                        [![Code Smells](https://sonarcloud.io/api/project_badges/measure?project=com.exasol%3Amy-project&metric=code_smells)](https://sonarcloud.io/dashboard?id=com.exasol%3Amy-project)
+                        [![Coverage](https://sonarcloud.io/api/project_badges/measure?project=com.exasol%3Amy-project&metric=coverage)](https://sonarcloud.io/dashboard?id=com.exasol%3Amy-project)
+                        [![Duplicated Lines (%)](https://sonarcloud.io/api/project_badges/measure?project=com.exasol%3Amy-project&metric=duplicated_lines_density)](https://sonarcloud.io/dashboard?id=com.exasol%3Amy-project)
+                        [![Lines of Code](https://sonarcloud.io/api/project_badges/measure?project=com.exasol%3Amy-project&metric=ncloc)](https://sonarcloud.io/dashboard?id=com.exasol%3Amy-project)
+
+                        ## Additional Information
+
+                        * [Changelog](doc/changes/changelog.md)
+                        * [Dependencies](dependencies.md)""")));
```
Comment (skyglass) [inline project-keeper/src/test/java/com/exasol/projectkeeper/validators/ReadmeFileValidatorTest.java:50]: As this string starts with indentation before and after """"", I think it would be better to also end this string with indentation before and after """""

File: project-keeper/src/test/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeReportRendererTest.java [hunk 3]
```diff
@@ -25,24 +25,48 @@ class DependencyChangeReportRendererTest {
     @Test
     void testRenderSingleSourceReport() {
         final NamedDependencyChangeReport namedReport = new NamedDependencyChangeReport("my-project", REPORT);
-        assertThat(render(namedReport), equalTo("## Dependency Updates\n" + "\n" + "### Compile Dependency Updates\n"
-                + "\n" + "* Added `com.example:my-lib:1.2.3`"));
+        assertThat(render(namedReport), equalTo("""
```
Comment (skyglass) [inline project-keeper/src/test/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeReportRendererTest.java:28]: same here for indentation

File: project-keeper/src/test/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeReportRendererTest.java [hunk 4]
```diff
@@ -25,24 +25,48 @@ class DependencyChangeReportRendererTest {
...
+                ## Dependency Updates
+
+                ### Compile Dependency Updates
+
+                * Added `com.example:my-lib:1.2.3`"""));
```
Comment (skyglass) [inline project-keeper/src/test/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeReportRendererTest.java:33]: same here for indentation

File: project-keeper/src/test/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeReportRendererTest.java [hunk 5]
```diff
@@ -25,24 +25,48 @@ class DependencyChangeReportRendererTest {
...
+
+                        #### Compile Dependency Updates
+
+                        * Added `com.example:my-lib:1.2.3`
+
+                        ### Project B
+
+                        #### Compile Dependency Updates
+
+                        * Added `com.example:my-lib:1.2.3`"""));
```
Comment (skyglass) [inline project-keeper/src/test/java/com/exasol/projectkeeper/validators/changesfile/dependencies/DependencyChangeReportRendererTest.java:54]: same here for indentation

File: project-keeper/src/test/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRendererTest.java [hunk 6]
```diff
@@ -26,41 +24,48 @@ void twoDependenciesSameLicense() {
...
+
+                        ## Compile Dependencies
+
+                        | Dependency  | License          |
+                        | ----------- | ---------------- |
+                        | [my-lib][0] | [MIT License][1] |
+
+                        [0]: https://example.com/mylib
+                        [1]: https://mit.edu
+                        """);
```
Comment (skyglass) [inline project-keeper/src/test/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRendererTest.java:68]: same here for indentation

File: project-keeper/src/test/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRendererTest.java [hunk 7]
```diff
@@ -71,17 +76,20 @@ void testDependencyWithPipeSymbol() {
...
+
+                        ## Compile Dependencies
+
+                        | Dependency   | License           |
+                        | ------------ | ----------------- |
+                        | [my\\|lib][0] | [MIT\\|License][1] |
+
+                        [0]: https://example.com/mylib
+                        [1]: https://mit.edu
+                        """);
```
Comment (skyglass) [inline project-keeper/src/test/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRendererTest.java:92]: same here for indentation

File: project-keeper/src/test/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRendererTest.java [hunk 8]
```diff
@@ -115,30 +123,30 @@ void testMultiProjectSetup() {
...
-        return Stream.of(lines).collect(Collectors.joining(this.NEWLINE, "", this.NEWLINE));
+                        ### Compile Dependencies
+
+                        | Dependency  | License          |
+                        | ----------- | ---------------- |
+                        | [my-lib][0] | [MIT License][1] |
+
+                        [0]: https://example.com/mylib
+                        [1]: https://mit.edu
+                        """);
```
Comment (skyglass) [inline project-keeper/src/test/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRendererTest.java:149]: same here for indentation before and after """""

File: project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileValidatorTest.java [hunk 9]
```diff
@@ -49,13 +49,15 @@ void testValidation() throws IOException {
...
-                                + "</plugin>"))//
+                        """
+                                E-PK-CORE-105: Invalid pom file 'pom.xml': Required property 'finalName' is missing in maven-assembly-plugin. Use the following template and set finalName:
+                                <plugin>
+                                    <artifactId>maven-assembly-plugin</artifactId>
+                                    <groupId>org.apache.maven.plugins</groupId>
+                                    <configuration>
+                                        <finalName>NAME_OF_YOUR_JAR</finalName>
+                                    </configuration>
+                                </plugin>"""))//
```
Comment (skyglass) [inline project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileValidatorTest.java:60]: same here for indentation before and after """""

File: project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileValidatorTest.java [hunk 10]
```diff
@@ -144,9 +146,10 @@ void testMissingGroupId() throws IOException {
         testMavenModel.setGroupId(null);
         testMavenModel.writeAsPomToProject(this.tempDir);
         final List<ValidationFinding> result = runValidator(null);
-        assertThat(result, hasFindingWithMessage("E-PK-CORE-102: Invalid pom file 'pom.xml':" //
-                + " Required property 'groupId' is missing." //
-                + " Please either set /project/groupId or /project/parent/groupId."));
+        assertThat(result, hasFindingWithMessage("""
+                E-PK-CORE-102: Invalid pom file 'pom.xml':\
+                 Required property 'groupId' is missing.\
+                 Please either set /project/groupId or /project/parent/groupId."""));
```
Comment (skyglass) [inline project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileValidatorTest.java:152]: same here for indentation

File: project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileValidatorTest.java [hunk 11]
```diff
@@ -208,11 +211,12 @@ void testInvalidParentTag() throws IOException {
...
-                + " Invalid /project/parent/artifactId." //
-                + " Expected value is 'my-test-project-generated-parent'."
-                + " The pom must declare 'pk_generated_parent.pom' as parent pom." //
-                + " Check the project-keeper user guide if you need a parent pom."));
+        assertThat(result, hasFindingWithMessage("""
+                E-PK-CORE-104: Invalid pom file 'pom.xml':\
+                 Invalid /project/parent/artifactId.\
+                 Expected value is 'my-test-project-generated-parent'.\
+                 The pom must declare 'pk_generated_parent.pom' as parent pom.\
+                 Check the project-keeper user guide if you need a parent pom."""));
```
Comment (skyglass) [inline project-keeper/src/test/java/com/exasol/projectkeeper/validators/pom/PomFileValidatorTest.java:219]: same here for indentation

**Review by skyglass — APPROVED** [review]

**Review by skyglass — APPROVED** [review]
