### PR TITLE
implemented fix

### LINKED ISSUE #436: Fix sporadic differences for file dependencies.md
For quite a while we observed inconsistent Project-Keeper findings regarding content of file `dependencies.md`.

#### Generated on local machine
- Names of plugins without prefix “Apache”
- License is “The Apache Software License”
- URLs use http

```
| [Maven Clean Plugin][78]      | [The Apache Software License, Version 2.0][10] |
| [Maven Resources Plugin][79]  | [The Apache Software License, Version 2.0][10] |
| [Maven Install Plugin][80]    | [The Apache Software License, Version 2.0][10] |
| [Maven Site Plugin 3][81]     | [The Apache Software License, Version 2.0][10] |

[78]: http://maven.apache.org/plugins/maven-clean-plugin/
[79]: http://maven.apache.org/plugins/maven-resources-plugin/
[80]: http://maven.apache.org/plugins/maven-install-plugin/
[81]: http://maven.apache.org/plugins/maven-site-plugin/
```

#### Generated remotely 
- Names of plugins have additional prefix “Apache”
- License is “Apache License”
- URLs use https
```

| [Apache Maven Clean Plugin][78]     | [Apache License, Version 2.0][27] |
| [Apache Maven Resources Plugin][79] | [Apache License, Version 2.0][27] |
| [Apache Maven Install Plugin][80]   | [Apache License, Version 2.0][27] |
| [Apache Maven Site Plugin][81]      | [Apache License, Version 2.0][27] |

[78]: https://maven.apache.org/plugins/maven-clean-plugin/
[79]: https://maven.apache.org/plugins/maven-resources-plugin/
[80]: https://maven.apache.org/plugins/maven-install-plugin/
[81]: https://maven.apache.org/plugins/maven-site-plugin/
```

### Work araound 

Currently users need to add the following line to file `.project-keeper.yml`, see projects [spark-connector](https://github.com/exasol/spark-connector) and [extension-manager](https://github.com/exasol/extension-manager) for example:

``` 
- regex: "(?s)E-PK-CORE-53: The dependencies.md file has outdated content.*"
```

### PR DESCRIPTION
**Pull request by ckunki**
fixes #436

### CODE REVIEW

File: project-keeper/src/main/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRenderer.java [hunk 1]
```diff
@@ -91,7 +91,11 @@ private String renderDependencyName(final ProjectDependency dependency,
     }
 
     private String renderLicense(final License license, final MarkdownReferenceBuilder markdownReferenceBuilder) {
-        return renderLink(license.getName(), license.getUrl(), markdownReferenceBuilder);
+        String name = license.getName();
+        if (Workarounds.ALTERNATING_DEPENDENCIES.isActive()) {
+            name = name.replace("The Apache Software License", "Apache License");
+        }
```
Comment (kaklakariada) [inline project-keeper/src/main/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRenderer.java:97]: Optional: You could move this to `Workarounds.ALTERNATING_DEPENDENCIES.getLicenseName(license)`.
Then the logic is centralized in a single place.

**Review by kaklakariada — CHANGES_REQUESTED** [review]

File: doc/changes/changes_2.10.0.md [hunk 2]
```diff
@@ -0,0 +1,55 @@
+# Project Keeper 2.10.0, released 2023-03-20
```
[the remark this answers is not in the document]
Comment (ckunki) [reply doc/changes/changes_2.10.0.md]: 👍

File: project-keeper/src/main/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRenderer.java (hunk 1 above)
Comment (ckunki) [reply project-keeper/src/main/java/com/exasol/projectkeeper/validators/dependencies/renderer/DependencyPageRenderer.java]: 👍
