### PR TITLE
#428: Fixed failure of GitHub Workflow `project-keeper-verify.yml`

### LINKED ISSUE #428: GitHub Workflow project-keeper-verify.yml fails when no NPM modules are present
Workflow `.github/workflows/project-keeper-verify.yml` fails in step `actions/setup-node` with the following error:

```
Run actions/setup-node@v3
  with:
    node-version: 16
    cache: npm
    cache-dependency-path: **/package-lock.json
    always-auth: false
    check-latest: false
    token: ***
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.18-10/x64
    JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.18-10/x64
Found in cache @ /opt/hostedtoolcache/node/16.19.0/x64
Environment details
  node: v16.19.0
  npm: 8.19.3
  yarn: 1.22.19
/opt/hostedtoolcache/node/16.19.0/x64/bin/npm config get cache
/home/runner/.npm
Error: Some specified paths were not resolved, unable to cache dependencies.
```

The reason is that the workflow specifies `cache-dependency-path: "**/package-lock.json"` but in non-npm projects this file is not present.

To solve this we need to remove the `actions/setup-node` step from the workflow if no npm module is present in `.project-keeper.yml`.

### PR DESCRIPTION
**Pull request by ckunki**
fixes #428

### CODE REVIEW

File: project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/FileTemplatesFactory.java [hunk 1]
```diff
@@ -19,12 +19,27 @@ class FileTemplatesFactory {
     private static final String POM_FILES_GENERATED = String.format("%-65s%s", "pk_generated_parent.pom",
             "linguist-generated=true");
 
+    private static final String NPM_SETUP = lines( //
+            "      - name: Set up NPM", //
+            "        uses: actions/setup-node@v3", //
+            "        with:", //
+            "          node-version: 16", //
```
Comment (kaklakariada) [inline project-keeper/src/main/java/com/exasol/projectkeeper/validators/files/FileTemplatesFactory.java:26]:
```suggestion
            "          node-version: 18", //
```
18 is the latest LTS version

File: project-keeper/src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java [hunk 2]
```diff
@@ -137,6 +139,7 @@ void testValidAfterFix() throws IOException {
     @ValueSource(booleans = { true, false })
     // [itest->dsn~dependency-section-in-changes_x.x.x.md-file-validator~1]
     void testChangesFileGeneration(final boolean released) throws IOException, GitAPIException {
+        LOGGER.info(this.projectDir.toString());
```
Comment (kaklakariada) [inline project-keeper/src/test/java/com/exasol/projectkeeper/ProjectKeeperIT.java:142]:
```suggestion
```

**Review by kaklakariada — CHANGES_REQUESTED** [review]

**Review by kaklakariada — APPROVED** [review]
