### PR TITLE
 #615: Add integration test with NPM

### LINKED ISSUE #615: PK fix fails for NPM projects finding Java version
```
Exception in thread "main" java.lang.IllegalStateException: No latest java version found in source java versions []
        at com.exasol.projectkeeper.validators.files.JavaVersionExtractor.lambda$getCurrentLatestVersion$0(JavaVersionExtractor.java:70)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at com.exasol.projectkeeper.validators.files.JavaVersionExtractor.getCurrentLatestVersion(JavaVersionExtractor.java:69)
        at com.exasol.projectkeeper.validators.files.JavaVersionExtractor.getNextVersion(JavaVersionExtractor.java:52)
        at com.exasol.projectkeeper.validators.files.FileTemplatesFactory.<init>(FileTemplatesFactory.java:38)
        at com.exasol.projectkeeper.validators.files.ProjectFilesValidator.validate(ProjectFilesValidator.java:42)
        at com.exasol.projectkeeper.ProjectKeeper.lambda$runValidation$1(ProjectKeeper.java:287)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.exasol.projectkeeper.ProjectKeeper.runValidation(ProjectKeeper.java:288)
        at com.exasol.projectkeeper.ProjectKeeper.runValidationPhases(ProjectKeeper.java:278)
        at com.exasol.projectkeeper.ProjectKeeper.fix(ProjectKeeper.java:260)
        at com.exasol.projectkeeper.cli.ProjectKeeperLauncher.runProjectKeeper(ProjectKeeperLauncher.java:73)
        at com.exasol.projectkeeper.cli.ProjectKeeperLauncher.start(ProjectKeeperLauncher.java:67)
        at com.exasol.projectkeeper.cli.ProjectKeeperLauncher.main(ProjectKeeperLauncher.java:61)
```

Workaround: Downgrade PK to 4.4.0

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #615

### CODE REVIEW

File: shared-test-setup/src/main/java/com/exasol/projectkeeper/test/NpmProjectFixture.java [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+                Source.builder().modules(emptySet()).type(SourceType.NPM).path(Path.of(PACKAGE_FILE_NAME)).build()));
+    }
+
+    public void prepareProjectFiles(final Builder configBuilder) {
+        this.writeConfig(configBuilder);
+        this.prepareProjectFiles();
+        execute(projectDir, "npm" + suffixForWindows(".cmd"), "install");
+    }
+
+    private String suffixForWindows(final String suffix) {
```
Comment (pj-spoelders) [inline shared-test-setup/src/main/java/com/exasol/projectkeeper/test/NpmProjectFixture.java:34]: Any specific reason you're passing in `.cmd` ? Why not make the function parameterless and let it return  `.cmd`?

Comment (kaklakariada) [reply shared-test-setup/src/main/java/com/exasol/projectkeeper/test/NpmProjectFixture.java:34]: Hmmm.... good point ;)

**Review by pj-spoelders — APPROVED** [review]

File: shared-test-setup/src/main/java/com/exasol/projectkeeper/test/NpmProjectFixture.java (hunk 1 above)
Comment (kaklakariada) [reply shared-test-setup/src/main/java/com/exasol/projectkeeper/test/NpmProjectFixture.java:34]: Merged this PR too early. I fixed this review finding in another PR: https://github.com/exasol/project-keeper/pull/629
