### PR TITLE
Bugfix/#282-fix-launching-go-binaries

### LINKED ISSUE #282: Tests fail if go/bin is not in the path
For me tests failed with: `E-PK-CORE-142: Error starting the 'go-licenses' binary.`

Then I ran `go install github.com/google/go-licenses@latest'` as suggested, but it did not help.

I found out that go installs the binary to `$GOHOME/bin`. Where `$GOHOME` is unset at my system and by that `~/go`.
After adding this to $PATH everything worked fine.

Ideas for a Solution:
* Add an entry to the developers guide
* Change lookup to also check the $GOHOME.

### LINKED ISSUE #284: Add go support to README.md

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #282
Closes #284

### CODE REVIEW

File: project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GoProcess.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+
+class GoProcess {
+    private static final Logger LOGGER = Logger.getLogger(GoProcess.class.getName());
+
+    private GoProcess() {
+        // not instantiable
+    }
+
+    static SimpleProcess start(final Path workingDirectory, final List<String> command) {
+        List<String> commandToExecute = new ArrayList<>(command);
```
Comment (jakobbraun) [inline project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GoProcess.java:18]: aff final modifiers

**Review by jakobbraun — CHANGES_REQUESTED** [review]

File: project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GoProcess.java (hunk 1 above)
Comment (kaklakariada) [reply project-keeper/src/main/java/com/exasol/projectkeeper/sources/analyze/golang/GoProcess.java]: ✅

**Review by jakobbraun — APPROVED** [review]
